export const MODULE_NAME = 'importer'

// @deprecated: old setting name
export const SETTING_IMPORT_HP_FP = 'import_hp_fp'
// @deprecated: old setting name
export const SETTING_IMPORT_BODYPLAN = 'import_bodyplan'
// @deprecated: old setting name
export const SETTING_IGNORE_IMPORT_NAME = 'ignore_import_name'
// @deprecated: old setting name
export const SETTING_BLOCK_IMPORT = 'block-import'
// @deprecated: old setting name
export const SETTING_AUTOMATICALLY_SET_IGNOREQTY = 'auto-ignore-qty'
// @deprecated: old setting name
export const SETTING_IMPORT_EXTENDED_VALUES_GCS = 'import_extended_values_gcs'
// @deprecated: old setting name
export const SETTING_IMPORT_FILE_ENCODING = 'import-file-encoding'
// @deprecated: old setting name
export const SETTING_USE_BROWSER_IMPORTER = 'use-browser-importer'
// @deprecated: old setting name
export const SETTING_ignoreImportQty = 'ignoreImportQty'
// @deprecated: old setting name
export const SETTING_OVERWRITE_PORTRAITS = 'overwrite-portraits'

export const AUTOMATICALLY_SET_IGNORE_QTY = `${MODULE_NAME}.auto-ignore-qty`
export const DISPLAY_PRESERVE_QTY_FLAG = `${MODULE_NAME}.display-preserve-qty-flag`
export const IMPORT_EXTENDED_VALUES_GCS = `${MODULE_NAME}.import-extended-values-gcs`
export const IMPORT_FILE_ENCODING = `${MODULE_NAME}.import-file-encoding`
export const ONLY_TRUSTED_IMPORT = `${MODULE_NAME}.only-trusted-import`
export const OVERWRITE_BODYPLAN = `${MODULE_NAME}.overwrite-bodyplan`
export const OVERWRITE_HP_FP = `${MODULE_NAME}.overwrite-hp-fp`
export const OVERWRITE_NAME = `${MODULE_NAME}.overwrite-name`
export const OVERWRITE_PORTRAITS = `${MODULE_NAME}.overwrite-portraits`
export const USE_BROWSER_IMPORTER = `${MODULE_NAME}.use-browser-importer`
