import eslint from '@eslint/js'
import eslintConfigPrettier from 'eslint-config-prettier'
import importPlugin from 'eslint-plugin-import'
import tseslint from 'typescript-eslint'

const foundryGlobals = {
  game: 'readonly',
  canvas: 'readonly',
  ui: 'readonly',
  foundry: 'readonly',
  CONFIG: 'readonly',
  CONST: 'readonly',
  Hooks: 'readonly',
  Actor: 'readonly',
  Item: 'readonly',
  Token: 'readonly',
  ChatMessage: 'readonly',
  Dialog: 'readonly',
  Application: 'readonly',
  FormApplication: 'readonly',
  Roll: 'readonly',
  Macro: 'readonly',
  User: 'readonly',
  Scene: 'readonly',
  Combat: 'readonly',
  Combatant: 'readonly',
  ActiveEffect: 'readonly',
  TextEditor: 'readonly',
  FilePicker: 'readonly',
  AudioHelper: 'readonly',
  SocketInterface: 'readonly',
  DocumentSheet: 'readonly',
  ActorSheet: 'readonly',
  ItemSheet: 'readonly',
  JournalEntry: 'readonly',
  Folder: 'readonly',
  Draggable: 'readonly',
  SortingHelpers: 'readonly',
  SearchFilter: 'readonly',
  HandlebarsHelpers: 'readonly',
  renderTemplate: 'readonly',
  getTemplate: 'readonly',
  loadTemplates: 'readonly',
  fromUuid: 'readonly',
  fromUuidSync: 'readonly',
  duplicate: 'readonly',
  mergeObject: 'readonly',
  setProperty: 'readonly',
  getProperty: 'readonly',
  hasProperty: 'readonly',
  expandObject: 'readonly',
  flattenObject: 'readonly',
  randomID: 'readonly',
  debounce: 'readonly',
  GURPS: 'readonly',
  $: 'readonly',
  jQuery: 'readonly',
  Handlebars: 'readonly',
  console: 'readonly',
  document: 'readonly',
  window: 'readonly',
  setTimeout: 'readonly',
  setInterval: 'readonly',
  clearTimeout: 'readonly',
  clearInterval: 'readonly',
  fetch: 'readonly',
  FormData: 'readonly',
  MutationObserver: 'readonly',
  libWrapper: 'readonly',
  SimpleCalendar: 'readonly',
  dragRuler: 'readonly',
  global: 'readonly',
  structuredClone: 'readonly',
  typePrototypes: 'readonly',
  _patchedFuncs: 'writable',
  XMLHttpRequest: 'readonly',
  performance: 'readonly',
  Image: 'readonly',
  ImagePopout: 'readonly',
  DragDrop: 'readonly',
  KeyboardManager: 'readonly',
  ImportSettings: 'readonly',
  version: 'readonly',
  xml: 'readonly',
}

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  eslintConfigPrettier,
  {
    ignores: ['dist/', 'node_modules/', 'lib/', 'dev-utilities/', 'build/', 'scripts/'],
  },
  {
    languageOptions: {
      globals: foundryGlobals,
    },
  },
  {
    files: ['**/*.ts'],
    languageOptions: {
      parserOptions: {
        project: true,
      },
    },
  },
  {
    files: ['**/*.js'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  {
    plugins: {
      import: importPlugin,
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/ban-ts-comment': 'warn',
      '@typescript-eslint/no-empty-object-type': 'warn',
      '@typescript-eslint/no-wrapper-object-types': 'warn',
      'no-unused-vars': 'off',
      'import/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
          'newlines-between': 'always',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      'import/newline-after-import': ['error', { count: 1 }],
      'padding-line-between-statements': [
        'error',
        { blankLine: 'always', prev: '*', next: 'return' },
        { blankLine: 'always', prev: ['const', 'let', 'var'], next: '*' },
        { blankLine: 'any', prev: ['const', 'let', 'var'], next: ['const', 'let', 'var'] },
        { blankLine: 'always', prev: 'directive', next: '*' },
        { blankLine: 'always', prev: '*', next: 'function' },
        { blankLine: 'always', prev: 'function', next: '*' },
        { blankLine: 'always', prev: '*', next: 'class' },
        { blankLine: 'always', prev: 'class', next: '*' },
        { blankLine: 'always', prev: 'block-like', next: '*' },
        { blankLine: 'always', prev: '*', next: 'block-like' },
      ],
    },
  }
)
