const PDF_MAPPINGS: Record<string, { name: string; link: string }> = {
  AA: { name: 'Alphabet Arcane', link: '' },
  AALS: { name: 'Alphabet Arcane: Lost Serifs', link: '' },
  'ACT1:': { name: 'Action 1: Heroes', link: 'http://www.warehouse23.com/products/gurps-action-1-heroes' },
  'ACT2:': { name: 'Action 2: Exploits', link: 'http://www.warehouse23.com/products/gurps-action-3-furious-fists' },
  'ACT3:': { name: 'Action 3: Furious Fists', link: '' },
  'ACT4:': { name: 'Action 4: Specialists', link: '' },
  'ACT5:': { name: 'Action 5: Dictionary of Danger', link: '' },
  'ACT6:': { name: 'Action 6: Tricked-Out Rides', link: '' },
  'ACT7:': { name: 'Action 7: Mercenaries', link: '' },
  'ACT9:': { name: 'Action 9: The City', link: '' },
  AD: { name: 'Adaptations', link: '' },
  'ATE1:': { name: 'After the End 1: Wastelanders', link: '' },
  'ATE2:': { name: 'After the End 2: The New World', link: '' },
  AS: { name: 'Aliens: Sparrials', link: '' },
  B: {
    name: 'Basic Set: Characters OR the combined Basic Set: Characters and Campaigns',
    link: 'http://www.warehouse23.com/products/gurps-basic-set-characters-and-campaigns',
  },
  BC: { name: 'Boardroom and Curia', link: '' },
  BCTR: { name: 'Boardroom and Curia: Tomorrow Rides', link: '' },
  BCW: { name: 'Steampunk Setting: The Broken Clockwork World', link: '' },
  BL: { name: 'Big Lizzie', link: '' },
  BS: { name: 'Banestorm', link: 'http://www.warehouse23.com/products/gurps-banestorm' },
  BSA: { name: 'Banestorm: Abydos', link: '' },
  BT: { name: 'Bio-Tech', link: '' },
  BX: { name: 'Basic Set: Campaigns', link: 'https://warehouse23.com/products/gurps-basic-set-campaigns' },
  C: { name: 'Crusades', link: '' },
  CA: { name: 'Casey & Andy', link: '' },
  'CN1:': { name: 'Creatures of the Night, Volume 1', link: '' },
  'CN2:': { name: 'Creatures of the Night, Volume 2', link: '' },
  'CN3:': { name: 'Creatures of the Night, Volume 3', link: '' },
  'CN4:': { name: 'Creatures of the Night, Volume 4', link: '' },
  'CN5:': { name: 'Creatures of the Night, Volume 5', link: '' },
  CS: { name: 'City Stats', link: '' },
  DB: { name: 'Transhuman Space: Deep Beyond (3E)', link: '' },
  'DF1:': {
    name: 'Dungeon Fantasy 1: Adventurers',
    link: 'http://www.warehouse23.com/products/gurps-dungeon-fantasy-1-adventurers-1',
  },
  'DF2:': { name: 'Dungeon Fantasy 2: Dungeons', link: '' },
  'DF3:': {
    name: 'Dungeon Fantasy 3: The Next Level',
    link: 'http://www.warehouse23.com/products/gurps-dungeon-fantasy-3-the-next-level-1',
  },
  'DF4:': {
    name: 'Dungeon Fantasy 4: Sages',
    link: 'http://www.warehouse23.com/products/gurps-dungeon-fantasy-4-sages-1',
  },
  'DF5:': { name: 'Dungeon Fantasy 5: Allies', link: '' },
  'DF6:': { name: 'Dungeon Fantasy 6: 40 Artifacts', link: '' },
  'DF7:': { name: 'Dungeon Fantasy 7: Clerics', link: '' },
  'DF8:': {
    name: 'Dungeon Fantasy 8: Treasure Tables',
    link: 'http://www.warehouse23.com/products/gurps-dungeon-fantasy-8-treasure-tables',
  },
  'DF9:': { name: 'Dungeon Fantasy 9: Summoners', link: '' },
  'DF10:': { name: 'Dungeon Fantasy 10: Taverns', link: '' },
  'DF11:': {
    name: 'Dungeon Fantasy 11: Power-Ups',
    link: 'http://www.warehouse23.com/products/gurps-dungeon-fantasy-11-power-ups',
  },
  'DF12:': {
    name: 'Dungeon Fantasy 12: Ninja',
    link: 'http://www.warehouse23.com/products/gurps-dungeon-fantasy-12-ninja',
  },
  'DF13:': {
    name: 'Dungeon Fantasy 13: Loadouts',
    link: 'http://www.warehouse23.com/products/gurps-dungeon-fantasy-13-loadouts',
  },
  'DF14:': {
    name: 'Dungeon Fantasy 14: Psi',
    link: 'http://www.warehouse23.com/products/gurps-dungeon-fantasy-14-psi',
  },
  'DF15:': { name: 'Dungeon Fantasy 15: Henchmen', link: '' },
  'DF16:': { name: 'Dungeon Fantasy 16: Wilderness Adventures', link: '' },
  'DF17:': { name: 'Dungeon Fantasy 17: Guilds', link: '' },
  'DF18:': { name: 'Dungeon Fantasy 18: Power Items', link: '' },
  'DF19:': { name: 'Dungeon Fantasy 19: Incantation Magic', link: '' },
  'DF20:': { name: 'Dungeon Fantasy 20: Slayers', link: '' },
  DFA: {
    name: 'Dungeon Fantasy RPG: Adventurers',
    link: 'http://www.warehouse23.com/products/dungeon-fantasy-roleplaying-game',
  },
  'DFA1:': { name: 'Dungeon Fantasy Adventure 1: Mirror of the Fire Demon', link: '' },
  'DFA2:': { name: 'Dungeon Fantasy Adventure 2: Tomb of the Dragon King', link: '' },
  'DFA3:': { name: 'Dungeon Fantasy Adventure 3: Deep Night and the Star', link: '' },
  DFCG: { name: 'Dungeon Fantasy Career Guide', link: '' },
  DFDB: { name: 'Dungeon Fantasy Denizens: Barbarians', link: '' },
  DFDS: { name: 'Dungeon Fantasy Denizens: Swashbucklers', link: '' },
  'DFE1:': { name: 'Dungeon Fantasy Encounters 1: The Pagoda of Worlds', link: '' },
  'DFE2:': { name: 'Dungeon Fantasy Encounters 2: The Room', link: '' },
  'DFE3:': { name: 'Dungeon Fantasy Encounters 3: The Carnival of Madness', link: '' },
  DFM: {
    name: 'Dungeon Fantasy RPG: Monsters',
    link: 'http://www.warehouse23.com/products/dungeon-fantasy-roleplaying-game',
  },
  'DFM1:': {
    name: 'Dungeon Fantasy Monsters 1',
    link: 'http://www.warehouse23.com/products/gurps-dungeon-fantasy-monsters-1',
  },
  'DFM2:': { name: 'Dungeon Fantasy Monsters 2: Icky Goo', link: '' },
  'DFM3:': { name: 'Dungeon Fantasy Monsters 3: Born of Myth & Magic', link: '' },
  'DFM4:': { name: 'Dungeon Fantasy Monsters 4: Dragons', link: '' },
  'DFM5:': { name: 'Dungeon Fantasy Monsters 5: Demons', link: '' },
  'DFMI1:': { name: 'Dungeon Fantasy RPG: Magic Items 1', link: '' },
  'DFMI2:': { name: 'Dungeon Fantasy RPG: Magic Items 2', link: '' },
  'DFRC2:': { name: 'Dungeon Fantasy RPG: Companion 2', link: '' },
  'DFRM2:': { name: 'Dungeon Fantasy RPG: Monsters 2', link: '' },
  DFS: {
    name: 'Dungeon Fantasy RPG: Spells',
    link: 'http://www.warehouse23.com/products/dungeon-fantasy-roleplaying-game',
  },
  DFSC: { name: 'Dungeon Fantasy Setting: Caverntown', link: '' },
  DFSCSM: { name: 'Dungeon Fantasy Setting: Cold Shard Mountain', link: '' },
  'DFT1:': { name: 'Dungeon Fantasy Treasures 1: Glittering Prizes', link: '' },
  'DFT2:': { name: 'Dungeon Fantasy Treasures 2: Epic Treasures', link: '' },
  'DFT3:': { name: 'Dungeon Fantasy Treasures 3: Artifacts of Felltower', link: '' },
  'DFT4:': { name: 'Dungeon Fantasy Treasures 4: Mixed Blessings', link: '' },
  DFX: {
    name: 'Dungeon Fantasy RPG: Exploits',
    link: 'http://www.warehouse23.com/products/dungeon-fantasy-roleplaying-game',
  },
  DH: { name: 'Disasters: Hurricane', link: '' },
  DL: { name: 'Deadlands: Weird West (3E)', link: '' },
  DLH: { name: 'Deadlands: Hexes (3E)', link: '' },
  DLV: { name: 'Deadlands: Varmints (3E)', link: '' },
  DMF: { name: 'Disasters: Meltdown and Fallout', link: '' },
  'DN1:': { name: 'Deadlands: Dime Novel 1 - Aces and Eights (3E)', link: '' },
  'DN2:': { name: 'Deadlands: Dime Novel 2 - Wanted: Undead or Alive (3E)', link: '' },
  DR: { name: 'Dragons', link: 'http://www.warehouse23.com/products/gurps-dragons-1' },
  DTG: { name: 'Delvers To Grow', link: '' },
  DW: { name: 'Discworld Roleplaying Game', link: '' },
  EHHC: { name: 'Encounter: The Harrowed Hearts Club', link: '' },
  F: { name: 'Fantasy', link: 'http://www.warehouse23.com/products/gurps-fantasy' },
  FD: { name: 'Fantastic Dungeon Grappling', link: 'https://warehouse23.com/products/fantastic-dungeon-grappling-pdf' },
  FED: { name: 'Federation', link: '' },
  FF: { name: 'Fantasy Folk (3E)', link: '' },
  FFE: { name: 'Fantasy Folk: Elves', link: '' },
  FFGH: { name: 'Fantasy Folk: Goblins and Hobgoblins', link: '' },
  FFK: { name: 'Fantasy Folk: Kobolds', link: '' },
  FFWF: { name: 'Fantasy Folk: Winged Folk', link: '' },
  FH: { name: 'Future History', link: '' },
  FPR: { name: 'Fantasy: Portal Realms', link: '' },
  'FT1:': { name: 'Fantasy-Tech 1: The Edge of Reality', link: '' },
  'FT2:': { name: 'Fantasy-Tech 2: Weapons of Fantasy', link: '' },
  FUR: { name: 'Furries', link: '' },
  FW: { name: 'Transhuman Space: Fifth Wave (3E)', link: '' },
  GF: { name: 'Gun Fu', link: '' },
  GG: { name: 'Girl Genius RPG', link: '' },
  GUL: { name: 'Gulliver Mini', link: '' },
  H: { name: 'Horror', link: 'http://www.warehouse23.com/products/gurps-horror-1' },
  HF: { name: 'Historical Folks', link: 'http://www.mygurps.com/historical_folks_4e.pdf' },
  HMD: { name: 'Horror: The Madness Dossier', link: '' },
  HOA: { name: 'Hand of Asgard', link: '' },
  HOSF: { name: 'Horror: The Old Stone Fort', link: '' },
  HOW: { name: 'How to Be a GURPS GM', link: '' },
  HOWRPM: { name: 'How to Be a GURPS GM: Ritual Path Magic', link: '' },
  HSC: { name: 'Hot Spots: Constantinople, 527-1204 A.D.', link: '' },
  HSIT: { name: 'Hot Spots: The Incense Trail', link: '' },
  HSRF: { name: 'Hot Spots: Renaissance Florence', link: '' },
  HSRV: { name: 'Hot Spots: Renaissance Venice', link: '' },
  HSS: { name: 'Hot Spots: Sriwijaya', link: '' },
  HSSR: { name: 'Hot Spots: The Silk Road', link: '' },
  HT: { name: 'High-Tech', link: 'http://www.warehouse23.com/products/gurps-high-tech-2' },
  HTAG: { name: 'High-Tech: Adventure Guns', link: '' },
  HTEE: { name: 'High-Tech: Electricity and Electronics', link: '' },
  'HTPG1:': { name: 'High-Tech: Pulp Guns 1', link: '' },
  'HTPG2:': { name: 'High-Tech: Pulp Guns 2', link: '' },
  HTWT: { name: 'High-Tech: Weapon Tables', link: '' },
  IW: { name: 'Infinite Worlds', link: 'http://www.warehouse23.com/products/gurps-infinite-worlds-1' },
  IWB: { name: 'Infinite Worlds: Britannica-6', link: '' },
  IWCJ: { name: 'Infinite Worlds: Collegio Januari', link: '' },
  IWLW: { name: 'Infinite Worlds: Lost Worlds', link: '' },
  IWWH: { name: 'Infinite Worlds: Worlds of Horror', link: '' },
  KL: { name: 'Klingons', link: '' },
  L: { name: 'Lite', link: 'https://warehouse23.com/products/gurps-lite-fourth-edition' },
  LFM: { name: 'Lair of the Fat Man', link: '' },
  LH: { name: 'Locations: Hellsgate', link: '' },
  LMM: { name: 'Locations: Metro of Madness', link: '' },
  LOLTA: { name: 'Loadouts: Low-Tech Armor', link: '' },
  LOMH: { name: 'Loadouts: Monster Hunters', link: '' },
  LOT: { name: 'Lands Out of Time', link: '' },
  LSGC: { name: "Locations: St. George's Cathedral", link: '' },
  LT: { name: 'Low-Tech', link: 'http://www.warehouse23.com/products/gurps-fourth-edition-low-tech' },
  'LTC1:': {
    name: 'Low-Tech Companion 1: Philosophers and Kings',
    link: 'http://www.warehouse23.com/products/gurps-low-tech-companion-1-philosophers-and-kings',
  },
  'LTC2:': { name: 'Low-Tech Companion 2: Weapons and Warriors', link: '' },
  'LTC3:': { name: 'Low-Tech Companion 3: Daily Life and Economics', link: '' },
  LTIA: { name: 'Low-Tech: Instant Armor', link: 'http://www.warehouse23.com/products/gurps-low-tech-instant-armor' },
  LTO: { name: 'Locations: Tower of Octavius', link: '' },
  LW: { name: 'Locations: Worminghall', link: '' },
  M: { name: 'Magic', link: 'http://www.warehouse23.com/products/gurps-magic-5' },
  MA: { name: 'Martial Arts', link: 'http://www.warehouse23.com/products/gurps-martial-arts' },
  MAFCCS: {
    name: 'Martial Arts: Fairbairn Close Combat Systems',
    link: 'http://www.warehouse23.com/products/gurps-martial-arts-fairbairn-close-combat-systems',
  },
  MAG: { name: 'Martial Arts: Gladiators', link: '' },
  MAS: { name: 'Magic: Artillery Spells', link: '' },
  MATG: {
    name: 'Martial Arts: Technical Grappling',
    link: 'http://www.warehouse23.com/products/gurps-martial-arts-technical-grappling',
  },
  MAYFS: { name: 'Martial Arts: Yrth Fighting Styles', link: '' },
  MC: { name: 'Mass Combat', link: '' },
  MDS: { name: 'Magic: Death Spells', link: '' },
  MGA: { name: 'MacGuffin Alphabet', link: '' },
  'MH1:': {
    name: 'Monster Hunters 1: Champions',
    link: 'http://www.warehouse23.com/products/gurps-monster-hunters-1-champions',
  },
  'MH2:': { name: 'Monster Hunters 2: The Mission', link: '' },
  'MH3:': { name: 'Monster Hunters 3: The Enemy', link: '' },
  'MH4:': { name: 'Monster Hunters 4: Sidekicks', link: '' },
  'MH5:': { name: 'Monster Hunters 5: Applied Xenology', link: '' },
  'MH6:': { name: 'Monster Hunters 6: Holy Hunters', link: '' },
  'MHE1:': { name: 'Monster Hunters Encounters 1', link: '' },
  'MHPU1:': { name: 'Monster Hunters Power-Ups 1', link: '' },
  MPS: { name: 'Magic: Plant Spells', link: 'http://www.warehouse23.com/products/gurps-magic-plant-spells' },
  MSDM: { name: 'Magical Styles: Dungeon Magic', link: '' },
  MSHM: { name: 'Magical Styles: Horror Magic', link: '' },
  MTLOS: { name: 'Magic: The Least of Spells', link: '' },
  MYST: { name: 'Mysteries', link: 'http://www.warehouse23.com/products/gurps-mysteries-1' },
  MYTH: { name: 'Myth (3E)', link: 'http://www.sjgames.com/gurps/books/myth/' },
  NBB: { name: 'Nordlondr Bestiary: Bugstiary', link: '' },
  NBE: {
    name: 'Nordlondr Bestiary and Enemies Book',
    link: 'http://github.com/mjeffw/nordlond-bestiary-public/blob/main/README.md',
  },
  NBG: { name: 'Nordlondr Bestiary: Garden of Evil', link: '' },
  NBS: { name: 'Nordlondr Bestiary: Serpents of Legend', link: '' },
  NF: { name: 'Nordlondr Folk', link: '' },
  P: { name: 'Powers', link: 'http://www.warehouse23.com/products/gurps-powers' },
  PC: { name: 'Psionic Campaigns', link: '' },
  PD: { name: 'Prime Directive', link: '' },
  PDF: { name: 'Powers: Divine Favor', link: 'http://www.warehouse23.com/products/gurps-powers-divine-favor' },
  PDFC: { name: 'Pyramid: Dungeon Fantasy Collected', link: '' },
  PES: { name: 'Powers: Enhanced Senses', link: '' },
  PSI: { name: 'Psionic Powers', link: 'http://www.warehouse23.com/products/gurps-psionic-powers' },
  PSIS: { name: 'Psis', link: '' },
  PT: { name: 'Psi-Tech', link: '' },
  PTNS: { name: 'Powers: Totems and Nature Spirits', link: '' },
  'PU1:': {
    name: 'Power-Ups 1: Imbuements',
    link: 'http://www.warehouse23.com/products/gurps-power-ups-1-imbuements-1',
  },
  'PU2:': { name: 'Power-Ups 2: Perks', link: 'http://www.warehouse23.com/products/gurps-power-ups-2-perks' },
  'PU3:': { name: 'Power-Ups 3: Talents', link: 'http://www.warehouse23.com/products/gurps-power-ups-3-talents' },
  'PU4:': { name: 'Power-Ups 4: Enhancements', link: '' },
  'PU5:': { name: 'Power-Ups 5: Impulse Buys', link: '' },
  'PU6:': { name: 'Power-Ups 6: Quirks', link: '' },
  'PU7:': { name: 'Power-Ups 7: Wildcard Skills', link: '' },
  'PU8:': { name: 'Power-Ups 8: Limitations', link: '' },
  'PU9:': { name: 'Power-Ups 9: Alternate Attributes', link: '' },
  PW: { name: 'Powers: The Weird', link: '' },
  'PY#:': { name: 'Pyramid 3 issue {issue}', link: 'https://warehouse23.com/search?q=pyramid+3-{issue}' },
  'PY4-#:': { name: 'Pyramid 4 issues (replace # with the issue number)', link: '' },
  PYDC: { name: 'Pyramid Dungeon Collection', link: '' },
  RM: { name: 'Realm Management', link: '' },
  ROM: { name: 'Romulans', link: '' },
  RSRS: { name: 'Reign of Steel: Read the Sky', link: '' },
  RSWL: {
    name: 'Reign of Steel: Will to Live',
    link: 'http://www.warehouse23.com/products/gurps-reign-of-steel-will-to-live',
  },
  S: { name: 'Space', link: '' },
  SCASPC: { name: 'Supporting Cast: Age of Sail Pirate Crew', link: '' },
  SE: { name: 'Social Engineering', link: '' },
  SEAL: { name: 'SEALs in Vietnam', link: '' },
  SEBS: { name: 'Social Engineering: Back to School', link: '' },
  SEKC: { name: 'Social Engineering: Keeping in Contact', link: '' },
  SEPR: { name: 'Social Engineering: Pulling Rank', link: '' },
  'SP1:': { name: 'Steampunk 1: Settings and Style', link: '' },
  'SP2:': { name: 'Steampunk 2: Steam and Shellfire', link: '' },
  'SP3:': { name: 'Steampunk 3: Soldiers and Scientists', link: '' },
  SPWS: { name: 'Sorcery: Protection and Warning Spells', link: '' },
  'SS1:': { name: 'Spaceships', link: '' },
  'SS2:': { name: 'Spaceships 2: Traders, Liners, and Transports', link: '' },
  'SS3:': { name: 'Spaceships 3: Warships and Space Pirates', link: '' },
  'SS4:': { name: 'Spaceships 4: Fighters, Carriers, and Mecha', link: '' },
  'SS5:': { name: 'Spaceships 5: Exploration and Colony Spacecraft', link: '' },
  'SS6:': { name: 'Spaceships 6: Mining and Industrial Spacecraft', link: '' },
  'SS7:': { name: 'Spaceships 7: Divergent and Paranormal Tech', link: '' },
  'SS8:': { name: 'Spaceships 8: Transhuman Spacecraft', link: '' },
  SSS: { name: 'Sorcery: Sound Spells', link: '' },
  SU: { name: 'Supers', link: 'http://www.warehouse23.com/products/gurps-supers-3' },
  T: { name: 'Thaumatology', link: '' },
  TAB: { name: 'Thaumatology: Alchemical Baroque', link: '' },
  TAG: { name: 'Thaumatology: Age of Gold', link: '' },
  TCEP: { name: 'Thaumatology: Chinese Elemental Powers', link: '' },
  THS: { name: 'Transhuman Space', link: '' },
  THSBB: { name: 'Transhuman Space: Bioroid Bazaar', link: '' },
  THSBT: { name: 'Transhuman Space: Bio-Tech 2100', link: '' },
  THSCE: { name: 'Transhuman Space: Cities on the Edge', link: '' },
  THSCT: { name: 'Transhuman Space: Changing Times', link: '' },
  THSMA: { name: 'Transhuman Space: Martial Arts 2100', link: '' },
  'THSPF2:': { name: 'Transhuman Space: Personnel Files 2 - The Meme Team', link: '' },
  'THSPF3:': { name: 'Transhuman Space: Personnel Files 3 - Wild Justice', link: '' },
  'THSPF4:': { name: 'Transhuman Space: Personnel Files 4 - Martingale Security', link: '' },
  'THSPF5:': { name: 'Transhuman Space: Personnel Files 5 - School Days 2100', link: '' },
  THSST: { name: 'Transhuman Space: Shell-Tech', link: '' },
  THSTM: { name: 'Transhuman Space: Transhuman Mysteries', link: '' },
  'THSTN1:': { name: 'Transhuman Space: Teralogos News - 2100, Fourth Quarter', link: '' },
  'THSTN2:': { name: 'Transhuman Space: Teralogos News - 2101, First Quarter', link: '' },
  'THSTN3:': { name: 'Transhuman Space: Teralogos News - 2101, Second Quarter', link: '' },
  'THSTN4:': { name: 'Transhuman Space: Teralogos News - 2101, Third Quarter', link: '' },
  THSTX: { name: 'Transhuman Space: Toxic Memes', link: '' },
  THSUP: { name: 'Transhuman Space: Under Pressure', link: '' },
  THSWRS: { name: 'Transhuman Space: Wings of the Rising Sun', link: '' },
  'TIW:': { name: 'Traveller: Interstellar Wars', link: '' },
  TMS: {
    name: 'Thaumatology: Magical Styles',
    link: 'http://www.warehouse23.com/products/gurps-thaumatology-magical-styles',
  },
  TRPM: {
    name: 'Thaumatology: Ritual Path Magic',
    link: 'http://www.warehouse23.com/products/gurps-thaumatology-ritual-path-magic',
  },
  TS: { name: 'Tactical Shooting', link: 'http://www.warehouse23.com/products/gurps-tactical-shooting' },
  TSOR: { name: 'Thaumatology: Sorcery', link: 'http://www.warehouse23.com/products/gurps-thaumatology-sorcery' },
  TSP: { name: 'Tales of the Solar Patrol', link: '' },
  'TT1:': { name: 'Template Toolkit 1: Characters', link: '' },
  'TT2:': { name: 'Template Toolkit 2: Races', link: '' },
  'TT3:': { name: 'Template Toolkit 3: Starship Crew', link: '' },
  TUM: { name: 'Thaumatology: Urban Magics', link: '' },
  UA: { name: 'Underground Adventures', link: '' },
  UL: { name: 'Ultra-Lite', link: '' },
  UT: { name: 'Ultra-Tech', link: 'http://www.warehouse23.com/products/gurps-ultra-tech' },
  UTWT: { name: 'Ultra-Tech: Weapon Tables', link: '' },
  VOR: {
    name: 'Vorkosigan Saga RPG',
    link: 'http://www.warehouse23.com/products/vorkosigan-saga-sourcebook-and-roleplaying-game',
  },
  VSC: { name: 'Vehicles: Steampunk Conveyances', link: '' },
  VTF: { name: 'Vehicles: Transports of Fantasy', link: '' },
  WK: { name: 'Warlock Knight', link: 'https://gaming-ballistic.myshopify.com/products/warlock-knight-vtt-module' },
  Z: { name: 'Zombies', link: '' },
  ZDO: { name: 'Zombies: Day One', link: '' },
  // Dungeon Fantasy Boxed Set code conventions used in GCA
  'DFRPG:A': {
    name: 'Dungeon Fantasy RPG: Adventurers',
    link: 'http://www.warehouse23.com/products/dungeon-fantasy-roleplaying-game',
  },
  'DFRPG:E': {
    name: 'Dungeon Fantasy RPG: Exploits',
    link: 'http://www.warehouse23.com/products/dungeon-fantasy-roleplaying-game',
  },
  'DFRPG:M': {
    name: 'Dungeon Fantasy RPG: Monsters',
    link: 'http://www.warehouse23.com/products/dungeon-fantasy-roleplaying-game',
  },
  'DFRPG:S': {
    name: 'Dungeon Fantasy RPG: Spells',
    link: 'http://www.warehouse23.com/products/dungeon-fantasy-roleplaying-game',
  },
}

/* ---------------------------------------- */

export { PDF_MAPPINGS }
