import { migrateLegacySettings } from '@module/migration/settings-migration.js'

import {
  SETTING_USE_ON_TARGET,
  SETTING_MANEUVER_VISIBILITY,
  SETTING_MANEUVER_DETAIL,
  SETTING_MANEUVER_UPDATES_MOVE,
  SETTING_ALLOW_ROLL_BASED_ON_MANEUVER,
  SETTING_INITIATIVE_FORMULA,
  SETTING_RANGE_STRATEGY,
  SETTING_USE_SIZE_MODIFIER_DIFFERENCE_IN_MELEE,
} from './settings.js'
import {
  OLD_SETTING_USE_ON_TARGET,
  OLD_SETTING_MANEUVER_VISIBILITY,
  OLD_SETTING_MANEUVER_DETAIL,
  OLD_SETTING_MANEUVER_UPDATES_MOVE,
  OLD_SETTING_ALLOW_ROLL_BASED_ON_MANEUVER,
  OLD_SETTING_INITIATIVE_FORMULA,
  OLD_SETTING_RANGE_STRATEGY,
  OLD_SETTING_USE_SIZE_MODIFIER_DIFFERENCE_IN_MELEE,
} from './types.js'

const migrations = [
  [OLD_SETTING_USE_ON_TARGET, SETTING_USE_ON_TARGET],
  [OLD_SETTING_MANEUVER_VISIBILITY, SETTING_MANEUVER_VISIBILITY],
  [OLD_SETTING_MANEUVER_DETAIL, SETTING_MANEUVER_DETAIL],
  [OLD_SETTING_MANEUVER_UPDATES_MOVE, SETTING_MANEUVER_UPDATES_MOVE],
  [OLD_SETTING_ALLOW_ROLL_BASED_ON_MANEUVER, SETTING_ALLOW_ROLL_BASED_ON_MANEUVER],
  [OLD_SETTING_INITIATIVE_FORMULA, SETTING_INITIATIVE_FORMULA],
  [OLD_SETTING_RANGE_STRATEGY, SETTING_RANGE_STRATEGY],
  [OLD_SETTING_USE_SIZE_MODIFIER_DIFFERENCE_IN_MELEE, SETTING_USE_SIZE_MODIFIER_DIFFERENCE_IN_MELEE],
].map(([oldName, newName]) => ({ oldName, newName, migrateValue: (value: unknown) => value }))

export function migrateCombatSettings(): void {
  if (!game.user?.isGM) return
  migrateLegacySettings('gurps', migrations)
}
