import { DataModel } from '@gurps-types/foundry/index.js'

import { GcsAttributeDefinition } from '../actor/data/gcs-character/attribute-definition.ts'

const DEFAULT_ATTRIBUTE_IDS = {
  st: 'wZ68WHN0uhJZvSCF',
  dx: '0wUa1JDYMjc0txYe',
  iq: '8eI5bzXxPqfbPLGP',
  ht: 'MlBNaEt4iigzA1rd',
  will: 'HRkHUpBfVpbrquR8',
  frightCheck: 'ABkaEHY7xDj915PI',
  per: 'rTHwfwWzeUqfpRnb',
  hearing: 'i9tghVfs6f7TO3Ph',
  vision: 'b2IVkRbqsTEMOIPR',
  tasteSmell: 'qLYzv2LMGhQWgAlF',
  touch: 'DyaOmYn1kJOneief',
  basicSpeed: 'GrqRcBoitbn9B4oc',
  basicMove: 'wZHlvCYD9h8MeVW2',
  fp: 'VPdAQJQ8PeC55EfR',
  hp: '1SRQfQ6FvUGgSF8T',
}

const HP_THRESHOLD_IDS = {
  healthy: 'hSFJCW2VNsQH2rLL',
  wounded: 'uJHn6UJwoQR8gPIY',
  reeling: 'lSwkxI2I7ZGMtgIa',
  collapse: '3wSwjb8OkyMx5T6r',
  dying1: 'CrWisd7BRLeiDSqp',
  dying2: 'JctKmZEZJqJpVmw1',
  dying3: '9MyZ4FvaSPN2nizJ',
  dying4: 'YYlG8Hor7AflzKSz',
  dead: 'vPyLXiMZuJyKBsgY',
}

const FP_THRESHOLD_IDS = {
  rested: 'S2qoUQgpJWwpYZVo',
  tiring: 'lzwgrLETMcQKhGXG',
  tired: 'foifZ4AEW21SlUXX',
  collapse: 'DRd1RLYrGVdL0M5z',
  unconscious: 'FP4NcZYCcjPK0Sjx',
}

const defaultAttributes = (): Record<string, DataModel.CreateData<DataModel.SchemaOf<GcsAttributeDefinition>>> => {
  return {
    [DEFAULT_ATTRIBUTE_IDS.st]: {
      _id: DEFAULT_ATTRIBUTE_IDS.st,
      sort: 0,
      attrId: 'st',
      type: GcsAttributeDefinition.TYPES.Integer,
      placement: GcsAttributeDefinition.PLACEMENTS.Automatic,
      base: '10',
      name: 'ST',
      fullName: 'Strength',
      costPerPoint: 10,
      costAdjPerSm: 10,
    },
    [DEFAULT_ATTRIBUTE_IDS.dx]: {
      _id: DEFAULT_ATTRIBUTE_IDS.dx,
      sort: 1,
      attrId: 'dx',
      type: GcsAttributeDefinition.TYPES.Integer,
      placement: GcsAttributeDefinition.PLACEMENTS.Automatic,
      base: '10',
      name: 'DX',
      fullName: 'Dexterity',
      costPerPoint: 20,
      costAdjPerSm: 0,
      _thresholds: null,
    },
    [DEFAULT_ATTRIBUTE_IDS.iq]: {
      _id: DEFAULT_ATTRIBUTE_IDS.iq,
      sort: 2,
      attrId: 'iq',
      type: GcsAttributeDefinition.TYPES.Integer,
      placement: GcsAttributeDefinition.PLACEMENTS.Automatic,
      base: '10',
      name: 'IQ',
      fullName: 'Intelligence',
      costPerPoint: 20,
      costAdjPerSm: 0,
      _thresholds: null,
    },
    [DEFAULT_ATTRIBUTE_IDS.ht]: {
      _id: DEFAULT_ATTRIBUTE_IDS.ht,
      sort: 3,
      attrId: 'ht',
      type: GcsAttributeDefinition.TYPES.Integer,
      placement: GcsAttributeDefinition.PLACEMENTS.Automatic,
      base: '10',
      name: 'HT',
      fullName: 'Health',
      costPerPoint: 10,
      costAdjPerSm: 0,
      _thresholds: null,
    },
    [DEFAULT_ATTRIBUTE_IDS.will]: {
      _id: DEFAULT_ATTRIBUTE_IDS.will,
      sort: 4,
      attrId: 'will',
      type: GcsAttributeDefinition.TYPES.Integer,
      placement: GcsAttributeDefinition.PLACEMENTS.Automatic,
      base: '$iq',
      name: 'Will',
      fullName: '',
      costPerPoint: 5,
      costAdjPerSm: 0,
      _thresholds: null,
    },
    [DEFAULT_ATTRIBUTE_IDS.frightCheck]: {
      _id: DEFAULT_ATTRIBUTE_IDS.frightCheck,
      sort: 5,
      attrId: 'fright_check',
      type: GcsAttributeDefinition.TYPES.Integer,
      placement: GcsAttributeDefinition.PLACEMENTS.Automatic,
      base: '$will',
      name: 'Fright Check',
      fullName: '',
      costPerPoint: 2,
      costAdjPerSm: 0,
      _thresholds: null,
    },
    [DEFAULT_ATTRIBUTE_IDS.per]: {
      _id: DEFAULT_ATTRIBUTE_IDS.per,
      sort: 6,
      attrId: 'per',
      type: GcsAttributeDefinition.TYPES.Integer,
      placement: GcsAttributeDefinition.PLACEMENTS.Automatic,
      base: '$iq',
      name: 'Per',
      fullName: 'Perception',
      costPerPoint: 5,
      costAdjPerSm: 0,
      _thresholds: null,
    },
    [DEFAULT_ATTRIBUTE_IDS.hearing]: {
      _id: DEFAULT_ATTRIBUTE_IDS.hearing,
      sort: 7,
      attrId: 'hearing',
      type: GcsAttributeDefinition.TYPES.Integer,
      placement: GcsAttributeDefinition.PLACEMENTS.Automatic,
      base: '$per',
      name: 'Hearing',
      fullName: '',
      costPerPoint: 2,
      costAdjPerSm: 0,
      _thresholds: null,
    },
    [DEFAULT_ATTRIBUTE_IDS.vision]: {
      _id: DEFAULT_ATTRIBUTE_IDS.vision,
      sort: 8,
      attrId: 'vision',
      type: GcsAttributeDefinition.TYPES.Integer,
      placement: GcsAttributeDefinition.PLACEMENTS.Automatic,
      base: '$per',
      name: 'Vision',
      fullName: '',
      costPerPoint: 2,
      costAdjPerSm: 0,
      _thresholds: null,
    },
    [DEFAULT_ATTRIBUTE_IDS.tasteSmell]: {
      _id: DEFAULT_ATTRIBUTE_IDS.tasteSmell,
      sort: 9,
      attrId: 'taste_smell',
      type: GcsAttributeDefinition.TYPES.Integer,
      placement: GcsAttributeDefinition.PLACEMENTS.Automatic,
      base: '$per',
      name: 'Taste & Smell',
      fullName: '',
      costPerPoint: 2,
      costAdjPerSm: 0,
      _thresholds: null,
    },
    [DEFAULT_ATTRIBUTE_IDS.touch]: {
      _id: DEFAULT_ATTRIBUTE_IDS.touch,
      sort: 10,
      attrId: 'touch',
      type: GcsAttributeDefinition.TYPES.Integer,
      placement: GcsAttributeDefinition.PLACEMENTS.Automatic,
      base: '$per',
      name: 'Touch',
      fullName: '',
      costPerPoint: 2,
      costAdjPerSm: 0,
      _thresholds: null,
    },
    [DEFAULT_ATTRIBUTE_IDS.basicSpeed]: {
      _id: DEFAULT_ATTRIBUTE_IDS.basicSpeed,
      sort: 11,
      attrId: 'basic_speed',
      type: GcsAttributeDefinition.TYPES.Decimal,
      placement: GcsAttributeDefinition.PLACEMENTS.Automatic,
      base: '($dx + $ht) / 4',
      name: 'Basic Speed',
      fullName: '',
      costPerPoint: 20,
      costAdjPerSm: 0,
      _thresholds: null,
    },
    [DEFAULT_ATTRIBUTE_IDS.basicMove]: {
      _id: DEFAULT_ATTRIBUTE_IDS.basicMove,
      sort: 12,
      attrId: 'basic_move',
      type: GcsAttributeDefinition.TYPES.Integer,
      placement: GcsAttributeDefinition.PLACEMENTS.Automatic,
      base: 'Math.floor($basic_speed)',
      name: 'Basic Move',
      fullName: '',
      costPerPoint: 5,
      costAdjPerSm: 0,
      _thresholds: null,
    },
    [DEFAULT_ATTRIBUTE_IDS.fp]: {
      _id: DEFAULT_ATTRIBUTE_IDS.fp,
      sort: 13,
      attrId: 'fp',
      type: GcsAttributeDefinition.TYPES.Pool,
      placement: GcsAttributeDefinition.PLACEMENTS.Automatic,
      base: '$ht',
      name: 'fp',
      fullName: 'Fatigue Points',
      costPerPoint: 3,
      costAdjPerSm: 0,
      _thresholds: {
        [FP_THRESHOLD_IDS.unconscious]: {
          _id: FP_THRESHOLD_IDS.unconscious,
          sort: 0,
          state: 'Unconscious',
          value: '-$fp',
          explanation: '',
          ops: [
            GcsAttributeDefinition.OPS.HalveMove,
            GcsAttributeDefinition.OPS.HalveDodge,
            GcsAttributeDefinition.OPS.HalveST,
          ],
        },
        [FP_THRESHOLD_IDS.collapse]: {
          _id: FP_THRESHOLD_IDS.collapse,
          sort: 1,
          state: 'Collapse',
          value: '0',
          explanation:
            '- Roll vs. Will to do anything besides talk or rest; failure causes unconsciousness\n' +
            '- Each FP you lose below 0 also causes 1 HP of injury\n' +
            '- Move, Dodge and ST are halved (B426)',
          ops: [
            GcsAttributeDefinition.OPS.HalveMove,
            GcsAttributeDefinition.OPS.HalveDodge,
            GcsAttributeDefinition.OPS.HalveST,
          ],
        },
        [FP_THRESHOLD_IDS.tired]: {
          _id: FP_THRESHOLD_IDS.tired,
          sort: 2,
          state: 'Tired',
          value: 'Math.ceil($fp / 3) - 1',
          explanation: 'Move, Dodge and ST are halved (B426)',
          ops: [
            GcsAttributeDefinition.OPS.HalveMove,
            GcsAttributeDefinition.OPS.HalveDodge,
            GcsAttributeDefinition.OPS.HalveST,
          ],
        },
        [FP_THRESHOLD_IDS.tiring]: {
          _id: FP_THRESHOLD_IDS.tiring,
          sort: 3,
          state: 'Tiring',
          value: '$fp - 1',
          explanation: '',
          ops: [],
        },
        [FP_THRESHOLD_IDS.rested]: {
          _id: FP_THRESHOLD_IDS.rested,
          sort: 4,
          state: 'Rested',
          value: '$fp',
          explanation: '',
          ops: [],
        },
      },
    },
    [DEFAULT_ATTRIBUTE_IDS.hp]: {
      _id: DEFAULT_ATTRIBUTE_IDS.hp,
      sort: 14,
      attrId: 'hp',
      type: GcsAttributeDefinition.TYPES.Pool,
      placement: GcsAttributeDefinition.PLACEMENTS.Automatic,
      base: '$st',
      name: 'hp',
      fullName: 'Hit Points',
      costPerPoint: 2,
      costAdjPerSm: 10,
      _thresholds: {
        [HP_THRESHOLD_IDS.dead]: {
          _id: HP_THRESHOLD_IDS.dead,
          sort: 0,
          state: 'Dead',
          value: 'Math.round(-$hp * 5)',
          explanation: '',
          ops: [GcsAttributeDefinition.OPS.HalveMove, GcsAttributeDefinition.OPS.HalveDodge],
        },
        [HP_THRESHOLD_IDS.dying4]: {
          _id: HP_THRESHOLD_IDS.dying4,
          sort: 1,
          state: 'Dying #4',
          value: 'Math.round(-$hp * 4)',
          explanation:
            '- Roll vs. HT to avoid death\n' +
            '- Roll vs. HT-4 every second to avoid falling unconscious\n' +
            '- Move and Dodge are halved (B419)\n',
          ops: [GcsAttributeDefinition.OPS.HalveMove, GcsAttributeDefinition.OPS.HalveDodge],
        },
        [HP_THRESHOLD_IDS.dying3]: {
          _id: HP_THRESHOLD_IDS.dying3,
          sort: 2,
          state: 'Dying #3',
          value: 'Math.round(-$hp * 3)',
          explanation:
            '- Roll vs. HT to avoid death\n' +
            '- Roll vs. HT-3 every second to avoid falling unconscious\n' +
            '- Move and Dodge are halved (B419)\n',
          ops: [GcsAttributeDefinition.OPS.HalveMove, GcsAttributeDefinition.OPS.HalveDodge],
        },
        [HP_THRESHOLD_IDS.dying2]: {
          _id: HP_THRESHOLD_IDS.dying2,
          sort: 3,
          state: 'Dying #2',
          value: 'Math.round(-$hp * 2)',
          explanation:
            '- Roll vs. HT to avoid death\n' +
            '- Roll vs. HT-2 every second to avoid falling unconscious\n' +
            '- Move and Dodge are halved (B419)\n',
          ops: [GcsAttributeDefinition.OPS.HalveMove, GcsAttributeDefinition.OPS.HalveDodge],
        },
        [HP_THRESHOLD_IDS.dying1]: {
          _id: HP_THRESHOLD_IDS.dying1,
          sort: 4,
          state: 'Dying #1',
          value: 'Math.round(-$hp * 1)',
          explanation:
            '- Roll vs. HT to avoid death\n' +
            '- Roll vs. HT-1 every second to avoid falling unconscious\n' +
            '- Move and Dodge are halved (B419)\n',
          ops: [GcsAttributeDefinition.OPS.HalveMove, GcsAttributeDefinition.OPS.HalveDodge],
        },
        [HP_THRESHOLD_IDS.collapse]: {
          _id: HP_THRESHOLD_IDS.collapse,
          sort: 5,
          state: 'Collapse',
          value: '0',
          explanation: '- Roll vs. HT every second to avoid falling unconscious' + '- Move and Dodge are halved (B419)',
          ops: [GcsAttributeDefinition.OPS.HalveMove, GcsAttributeDefinition.OPS.HalveDodge],
        },
        [HP_THRESHOLD_IDS.reeling]: {
          _id: HP_THRESHOLD_IDS.reeling,
          sort: 6,
          state: 'Reeling',
          value: 'Math.ceil($hp / 3) - 1',
          explanation: 'Move and Dodge are halved (B419)',
          ops: [GcsAttributeDefinition.OPS.HalveMove, GcsAttributeDefinition.OPS.HalveDodge],
        },
        [HP_THRESHOLD_IDS.wounded]: {
          _id: HP_THRESHOLD_IDS.wounded,
          sort: 7,
          state: 'Wounded',
          value: '$hp - 1',
          explanation: '',
          ops: [],
        },
        [HP_THRESHOLD_IDS.healthy]: {
          _id: HP_THRESHOLD_IDS.healthy,
          sort: 8,
          state: 'Healthy',
          value: '$hp',
          explanation: '',
          ops: [],
        },
      },
    },
  }
}

/* ---------------------------------------- */

export { defaultAttributes }
