import { DataModel } from '@gurps-types/foundry/index.js'
import { HitLocationEntryV2 } from '@module/actor/data/hit-location-entry.js'

export const defaultHitLocations = (): Record<
  string,
  Partial<DataModel.CreateData<DataModel.SchemaOf<HitLocationEntryV2>>>
> => {
  const locations: Partial<DataModel.CreateData<DataModel.SchemaOf<HitLocationEntryV2>>>[] = [
    {
      name: '',
      where: 'Eyes',
      import: 0,
      penalty: -9,
      rollText: '-',
      role: 'eye',
      _dr: 0,
      _damageType: null,
      split: {},
      drMod: 0,
      drItem: 0,
      drCap: 0,
      sort: 0,
    },
    {
      name: '',
      where: 'Skull',
      import: 2,
      penalty: -7,
      rollText: '3-4',
      role: 'skull',
      _dr: 2,
      _damageType: null,
      split: {},
      drMod: 0,
      drItem: 0,
      drCap: 0,
      sort: 100000,
    },
    {
      name: '',
      where: 'Face',
      import: 0,
      penalty: -5,
      rollText: '5',
      role: 'face',
      _dr: 0,
      _damageType: null,
      split: {},
      drMod: 0,
      drItem: 0,
      drCap: 0,
      sort: 200000,
    },
    {
      name: '',
      where: 'Right Leg',
      import: 0,
      penalty: -2,
      rollText: '6-7',
      role: 'limb',
      _dr: 0,
      _damageType: null,
      split: {},
      drMod: 0,
      drItem: 0,
      drCap: 0,
      sort: 300000,
    },
    {
      name: '',
      where: 'Right Arm',
      import: 0,
      penalty: -2,
      rollText: '8',
      role: 'limb',
      _dr: 0,
      _damageType: null,
      split: {},
      drMod: 0,
      drItem: 0,
      drCap: 0,
      sort: 400000,
    },
    {
      name: '',
      where: 'Torso',
      import: 0,
      penalty: 0,
      rollText: '9-10',
      role: 'chest',
      _dr: 0,
      _damageType: null,
      split: {},
      drMod: 0,
      drItem: 0,
      drCap: 0,
      sort: 500000,
    },
    {
      name: '',
      where: 'Groin',
      import: 0,
      penalty: -3,
      rollText: '11',
      role: 'groin',
      _dr: 0,
      _damageType: null,
      split: {},
      drMod: 0,
      drItem: 0,
      drCap: 0,
      sort: 600000,
    },
    {
      name: '',
      where: 'Left Arm',
      import: 0,
      penalty: -2,
      rollText: '12',
      role: 'limb',
      _dr: 0,
      _damageType: null,
      split: {},
      drMod: 0,
      drItem: 0,
      drCap: 0,
      sort: 700000,
    },
    {
      name: '',
      where: 'Left Leg',
      import: 0,
      penalty: -2,
      rollText: '13-14',
      role: 'limb',
      _dr: 0,
      _damageType: null,
      split: {},
      drMod: 0,
      drItem: 0,
      drCap: 0,
      sort: 800000,
    },
    {
      name: '',
      where: 'Hand',
      import: 0,
      penalty: -4,
      rollText: '15',
      role: 'extremity',
      _dr: 0,
      _damageType: null,
      split: {},
      drMod: 0,
      drItem: 0,
      drCap: 0,
      sort: 900000,
    },
    {
      name: '',
      where: 'Foot',
      import: 0,
      penalty: -4,
      rollText: '16',
      role: 'extremity',
      _dr: 0,
      _damageType: null,
      split: {},
      drMod: 0,
      drItem: 0,
      drCap: 0,
      sort: 1000000,
    },
    {
      name: '',
      where: 'Neck',
      import: 0,
      penalty: -5,
      rollText: '17-18',
      role: 'neck',
      _dr: 0,
      _damageType: null,
      split: {},
      drMod: 0,
      drItem: 0,
      drCap: 0,
      sort: 1100000,
    },
    {
      name: '',
      where: 'Vitals',
      import: 0,
      penalty: -3,
      rollText: '-',
      role: 'vitals',
      _dr: 0,
      _damageType: null,
      split: {},
      drMod: 0,
      drItem: 0,
      drCap: 0,
      sort: 1200000,
    },
  ]

  return Object.fromEntries(
    locations.map(location => {
      location._id = foundry.utils.randomID()

      return [location._id, location]
    })
  )
}
